package com.artisans.qwikhomeservices.utils;

public final class MyConstants {
    public static final String PREFS = "prefs";
    public static final String IS_DIALOG_SHOWN = "dialogShown";
    public static final String ITEM_NAME = "itemName";
    public static final String ITEM_PHOTO = "itemPhoto";
    public static final String ITEM_PRICE = "itemPrice";
    public static final String ITEM_REASON = "itemReason";
    public static final String PROFILE_FRAGMENT_TAG = "profileFrag";
    public static final String SERVICES = "Services";
    public static final String BARBERS = "Barbers";
    public static final String CARPENTERS = "Carpenters";
    public static final String MECHANICS = "Mechanics";
    public static final String PLUMBERS = "Plumbers";
    public static final String PEST_CONTROLS = "Pest Controls";
    public static final String TV_INSTALLERS = "Tv Installers";
    public static final String ROLLERS = "Rollers";
    public static final String TILERS = "Tilers";
    public static final String GARDENERS = "Gardeners";
    public static final String PAINTERS = "Painters";
    public static final String WELDERS = "Welders";
    public static final String WOMEN_HAIR_STYLIST = "Women Hairstylists";
    public static final String INTERIOR_DERCORATOR = "Interior Decorators";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String HASH_TYPE = "SHA-256";
    public static final int NUM_HASHED_BYTES = 9;
    public static final int NUM_BASE64_CHAR = 11;
    public static final String FIRST_NAME = "firstName";
    public static final String FULL_NAME = "fullName";
    public static final String ADAPTER_POSITION = "adapterPosition";
    public static final String LAST_NAME = "lastName";
    public static final String ACCOUNT_TYPE = "accountType";
    public static final String NAME = "name";
    public static final String ABOUT = "about";
    public static final String IMAGE_URL = "imageUrl";
    public static final String UID = "uid";
    public static final String RECEIVER_ID = "receiverId";
    public static final String SENDER_ID = "senderId";
    public static final String USER_IMAGE_URL = "userImageUrl";
    public static final String SEND_REQUEST_TAG = "sendRequest";
    public static final String STYLE = "style";
    public static final String PRICE = "price";
    public static final int REQUEST_CODE = 100;
    public static final String SERVICE_PERSON_NAME = "servicePersonName";
}
